#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='↱[\e[94m\u\e[32m@\e[93m\h\e[39m]⇔[\e[96m\w\e[39m]\n↳ '

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#neofetch

PATH="$HOME/.scripts:$PATH"
export PATH
